apiVersion: v1
kind: Service
metadata:
  name: iperf3-service
spec:
  type: NodePort
  selector:
    app: iperf3
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 5201
      targetPort: 5201
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007